name: Go
on:
  push:
  # branches:
  #   - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - uses: actions/setup-go@v3
        with:
          go-version: stable
      - run: go build -v ./...
      - run: go test -v -race ./...
